import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
const env = Object.fromEntries(readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')).trim(),l.slice(l.indexOf('=')+1).trim().replace(/^["']|["']$/g,'')]));
const admin = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const D = [
 {name:"Cross-Court Consistency Rally",category:"groundstrokes",skills:["forehand","backhand","consistency","depth"],level:"intermediate",min_players:2,max_players:4,duration_min:12,is_game:false,setup:"Two players cross-court on the deuce diagonal. Cones at the service line and 3ft inside the baseline mark the deep third.",instructions:"Rally cross-court cooperatively, landing every ball in the deep-third target. Count consecutive balls in the zone; reset the count on any error.",coaching_points:"Early unit turn, contact out front, recover to the center after every ball.",progression:"Set a target streak (e.g. 15), switch to the ad diagonal, then play the point live after 8 cooperative balls.",tags:["rally","target","cooperative"]},
 {name:"Serve Targets: Corners & Body",category:"serve",skills:["serve","spin","strategy"],level:"all",min_players:1,max_players:6,duration_min:15,is_game:false,setup:"Place three targets in each service box: wide, body, and T.",instructions:"Serve rounds of six (two to each target) on the deuce side, then the ad side. Score one point per target hit.",coaching_points:"Keep the same toss location for every target, disguise direction, brush up for spin on the wide serve.",progression:"Play serve golf: fewest misses over 18 serves wins, then add a returner.",tags:["accuracy","serve-golf"]},
 {name:"Two-Ball Volley Reflex",category:"volley",skills:["volley","footwork"],level:"intermediate",min_players:2,max_players:3,duration_min:8,is_game:false,setup:"Feeder at the service line holding two balls, player at the net.",instructions:"Feeder rapidly feeds alternating forehand and backhand volleys. Player punches each back and split-steps between feeds.",coaching_points:"Short backswing, firm wrist, meet the ball in front, split on the feed.",progression:"Increase pace, then add a low volley and finish with a swinging volley.",tags:["reflex","hand-feed"]},
 {name:"King of the Court",category:"game",skills:["strategy","consistency","serve"],level:"all",min_players:4,max_players:8,duration_min:20,is_game:true,setup:"One side is the King side; challengers queue behind the far baseline.",instructions:"A challenger feeds in and plays out the point against the King. Winner is King; loser rotates to the back of the line. First to hold a target number of points wins.",coaching_points:"Reward first-ball control; challengers must start the point reliably in play.",progression:"Serve to start instead of a feed, or require the King to win by two to advance.",tags:["competitive","rotation","clinic"]},
 {name:"Spider Run Footwork",category:"movement",skills:["footwork","fitness"],level:"all",min_players:1,max_players:8,duration_min:6,is_game:false,setup:"Five balls placed: both baseline corners, both sideline/service-line junctions, and the center mark.",instructions:"From the center hash, sprint to retrieve one ball at a time and return it to center until all five are moved. Time each player.",coaching_points:"Low first step, push off the outside foot, place the ball under control at center.",progression:"Race head-to-head, or add a shadow swing at each ball before returning it.",tags:["conditioning","timed","warmup"]},
 {name:"Approach & Volley Ladder",category:"strategy",skills:["volley","footwork","strategy"],level:"advanced",min_players:2,max_players:4,duration_min:12,is_game:false,setup:"Feeder at the baseline, player starting at the baseline.",instructions:"A short ball is fed; player hits an approach down the line, closes, plays a first volley, then a second volley to finish. Coach feeds the passing shot.",coaching_points:"Split-step as the opponent contacts, approach deep, close inside the service line to volley.",progression:"Use live passing shots, then add a lob option so the player handles an overhead.",tags:["transition","net"]},
 {name:"Mini-Tennis Dice",category:"warmup",skills:["consistency","spin","footwork"],level:"beginner",min_players:2,max_players:6,duration_min:8,is_game:true,setup:"Service boxes only, one die per pair.",instructions:"Rally inside the service boxes. When a pair reaches the target number of cooperative balls they roll the die, and that number becomes the next target.",coaching_points:"Racquet-head speed with control, use the whole box, small recovery steps.",progression:"Add a mini-point after six cooperative balls.",tags:["warmup","control","fun"]},
 {name:"Return Depth Gauntlet",category:"strategy",skills:["backhand","forehand","depth","strategy"],level:"intermediate",min_players:2,max_players:4,duration_min:10,is_game:false,setup:"Server serves; returner aims past a rope or cones set 5ft inside the baseline.",instructions:"Returner scores 2 for a deep return, 1 for an in-play shallow return, 0 for a miss. Ten returns on each side.",coaching_points:"Split on the serve, short backswing, drive through the deep central target under pressure.",progression:"Play the point out after the return; a deep return starts the point at 15-0.",tags:["return","target"]},
 {name:"Two-on-One Live Ball",category:"conditioning",skills:["consistency","footwork","fitness","strategy"],level:"advanced",min_players:3,max_players:3,duration_min:12,is_game:false,setup:"One player at the baseline versus two feeders.",instructions:"The two feed live balls side to side; the single keeps every ball in play, moving continuously for 90 seconds, then rotate.",coaching_points:"Hit neutral, deep balls under fatigue; recover to center; breathe and reset.",progression:"Allow the single to try to win the point on any short ball.",tags:["fitness","live-ball","rotation"]},
 {name:"Overhead & Recover",category:"overhead",skills:["overhead","footwork"],level:"intermediate",min_players:2,max_players:4,duration_min:8,is_game:false,setup:"Player at the net, coach lobbing.",instructions:"Coach lobs; player uses a crossover step back, hits the overhead, recovers forward to touch the net, and repeats for eight lobs.",coaching_points:"Turn sideways immediately, point at the ball with the non-hitting hand, contact out front and up.",progression:"Alternate a deep (bounce) overhead and a short (in-air) overhead, then play live after the overhead.",tags:["footwork","net"]},
 {name:"Serve +1 Pattern",category:"serve",skills:["serve","forehand","strategy"],level:"advanced",min_players:2,max_players:4,duration_min:14,is_game:false,setup:"Server and returner with target zones for the plus-one forehand.",instructions:"Serve wide to open the court, then run around the return and hit the plus-one forehand into the open court. Score each completed pattern.",coaching_points:"Recover to the plus-one position, explode to the forehand, big-cross or down-line into the open court.",progression:"Returner tries to neutralize; the server must still execute the pattern.",tags:["patterns","plus-one"]},
 {name:"Dingles",category:"game",skills:["doubles","volley","strategy"],level:"all",min_players:4,max_players:4,duration_min:18,is_game:true,setup:"Full doubles court, all four players in position.",instructions:"Coach feeds two balls at once (one cross to each pair). Both points play out simultaneously; a team must win BOTH balls to score, and the last ball standing decides.",coaching_points:"Communication, poaching, and court coverage under chaos.",progression:"Feed both balls at the same team to pressure their defense.",tags:["doubles","clinic","fun","competitive"]},
 {name:"Baseline Dropshot Read",category:"strategy",skills:["footwork","strategy","consistency"],level:"advanced",min_players:2,max_players:2,duration_min:10,is_game:false,setup:"Two players rallying deep, drop shot allowed at any time.",instructions:"Cooperative deep rally where either player may drop shot. The opponent must read it, sprint, and neutralize with a deep reply or a counter-drop.",coaching_points:"Stay low and split, disguise the drop with the same preparation as a drive.",progression:"Make it a live point the moment a drop shot is played.",tags:["touch","reaction"]},
 {name:"Figure-8 Volley Control",category:"volley",skills:["volley","consistency"],level:"intermediate",min_players:2,max_players:2,duration_min:8,is_game:false,setup:"Both players at the net at opposite service lines.",instructions:"One player volleys straight while the other volleys cross, so the balls travel in a continuous figure-8. Switch directions on the coach's call.",coaching_points:"Control over pace, angle the racquet face, take small adjusting steps.",progression:"Count consecutive volleys, then add a half-volley pickup.",tags:["control","cooperative"]},
 {name:"First-Ball Attack",category:"strategy",skills:["forehand","serve","strategy"],level:"intermediate",min_players:2,max_players:6,duration_min:12,is_game:true,setup:"Server serves and the coach feeds a floaty reply.",instructions:"After the serve the coach feeds a short ball; the server must attack it with a drive or approach and finish. Score only if the attack ball is genuinely aggressive and in.",coaching_points:"Move forward through the attack ball and decide early: drive or approach.",progression:"Replace the coach feed with a live returner.",tags:["aggression","first-strike"]},
 {name:"Around the World",category:"warmup",skills:["consistency","footwork","fitness"],level:"beginner",min_players:6,max_players:12,duration_min:8,is_game:true,setup:"Players split into two lines behind opposite baselines, one ball in play.",instructions:"Coach feeds; the first player hits and runs around the net post to the back of the other line. A miss costs a life; last player standing wins.",coaching_points:"Simple controlled shot, quick feet to the next line.",progression:"Add a second ball, or require a specific shot such as all backhands.",tags:["clinic","fun","large-group","warmup"]},
 {name:"Deep-Deep-Short Pattern",category:"groundstrokes",skills:["depth","forehand","backhand","footwork"],level:"intermediate",min_players:2,max_players:3,duration_min:10,is_game:false,setup:"Feeder alternates two deep balls and then one short ball.",instructions:"Player hits two deep drives from the baseline, then moves up to attack the short ball and recovers. Repeat the pattern.",coaching_points:"Handle the change of direction and forward transition; stay balanced on the short-ball attack.",progression:"Player finishes the short ball at the net with a volley.",tags:["pattern","movement"]},
 {name:"Tiebreak Pressure Sets",category:"game",skills:["serve","strategy","consistency"],level:"all",min_players:2,max_players:4,duration_min:15,is_game:true,setup:"Standard court.",instructions:"Play 7-point tiebreaks only, rotating opponents after each. Track a running win total across the clinic.",coaching_points:"Use routines between points and a high first-serve percentage under pressure.",progression:"Start each breaker at 3-3 to maximize pressure repetitions.",tags:["competitive","pressure","match-play"]},
 {name:"Volley-to-Volley Attack",category:"volley",skills:["volley","doubles","strategy"],level:"advanced",min_players:2,max_players:4,duration_min:10,is_game:false,setup:"Both players start at the net at the service lines.",instructions:"Live volley battle with the goal of hitting down at the opponent's feet while moving forward to close. The point ends on an error or a clean winner.",coaching_points:"Punch down at the feet, take time away by closing, keep the racquet up.",progression:"One player starts a step back and must fight forward.",tags:["net-battle","doubles"]},
 {name:"Ball-Machine Recovery Sprints",category:"conditioning",skills:["footwork","fitness","consistency"],level:"intermediate",min_players:1,max_players:2,duration_min:10,is_game:false,setup:"Ball machine set wide-to-wide at medium pace.",instructions:"Hit every ball corner to corner for 60-90 seconds, forcing a full recovery step to center between shots. Rest 45 seconds and repeat four rounds.",coaching_points:"Explosive recovery and controlled deep targets even while fatigued.",progression:"Increase the feed rate or add an approach on any slower ball.",tags:["fitness","machine","intervals"]},
 {name:"Half-Volley Pickup",category:"volley",skills:["volley","footwork","consistency"],level:"advanced",min_players:2,max_players:2,duration_min:8,is_game:false,setup:"One player at the service line, feeder at the baseline.",instructions:"Feeder drives balls at the feet; the player half-volleys deep, staying low, then transitions to a normal volley as balls come higher.",coaching_points:"Racquet down and firm, cushion the ball, bend the knees rather than leaning back.",progression:"Add movement: half-volley and then close for the finish.",tags:["transition","touch"]},
 {name:"Down-the-Line Duel",category:"groundstrokes",skills:["forehand","backhand","depth","strategy"],level:"advanced",min_players:2,max_players:2,duration_min:10,is_game:true,setup:"Both players hit only down the line, one on the forehand line and one on the backhand line.",instructions:"Live points in which every ball must land in the singles corridor down the line; any off-target ball loses the point.",coaching_points:"Precision and depth on the harder line shot; hold your ground.",progression:"Switch sides so each player rallies the other wing.",tags:["precision","live-point"]},
 {name:"Serve & Volley Builder",category:"strategy",skills:["serve","volley","footwork"],level:"advanced",min_players:2,max_players:4,duration_min:12,is_game:false,setup:"Server and returner.",instructions:"Serve, split-step near the service line, hit a first volley deep to a target, then close for the finish. Score each completed serve-and-volley pattern.",coaching_points:"Get the split before contact, hit the low first volley deep, close the second ball.",progression:"Returner attacks the return to test the low volley.",tags:["serve-volley","pattern"]},
 {name:"Consistency Clock to 21",category:"game",skills:["consistency","depth","footwork"],level:"beginner",min_players:2,max_players:4,duration_min:12,is_game:true,setup:"Half-court or full-court rally.",instructions:"Rally cooperatively to 21 in a row as a team; every miss resets the count to zero. Try to beat your previous best.",coaching_points:"Big margin over the net, deep central targets, calm feet.",progression:"Shrink the court to challenge control, or add a no-ball-above-the-shoulder rule.",tags:["cooperative","control","beginner"]},
 {name:"Inside-Out Forehand Rounds",category:"groundstrokes",skills:["forehand","footwork","strategy"],level:"advanced",min_players:2,max_players:4,duration_min:10,is_game:false,setup:"Feeder to the backhand corner with a big cross-court target for the inside-out forehand.",instructions:"Player runs around the backhand to hit eight inside-out forehands to the deep cross target, then switches to the inside-in variation.",coaching_points:"Get around the ball early, keep the deep cross target, recover the open court.",progression:"Feeder plays the reply into the open court to test recovery.",tags:["weapon","pattern"]},
 {name:"Poach Timing Drill",category:"strategy",skills:["doubles","volley","strategy"],level:"intermediate",min_players:3,max_players:4,duration_min:10,is_game:false,setup:"Doubles: server and net partner versus a returner.",instructions:"Server serves; the net partner reads the return and poaches, closing diagonally to put away the volley. Repeat on both sides.",coaching_points:"Move on the return contact, not before, and cross diagonally to cut the ball off.",progression:"Add a live opposing net player to defend the poach.",tags:["doubles","movement","timing"]},
 {name:"Drop-Feed Rhythm Warmup",category:"warmup",skills:["forehand","backhand","consistency"],level:"beginner",min_players:2,max_players:8,duration_min:6,is_game:false,setup:"Players in pairs, one partner drop-feeding.",instructions:"Partner drop-feeds forehands then backhands; the hitter grooves ten of each with relaxed, full swings before live rallying.",coaching_points:"Smooth tempo, full finish, watch the ball all the way to the strings.",progression:"Move to a live cooperative rally once the rhythm is set.",tags:["warmup","grooving"]},
 {name:"Corners & Middle Decision",category:"strategy",skills:["strategy","footwork","depth"],level:"intermediate",min_players:2,max_players:3,duration_min:10,is_game:false,setup:"Coach feeds unpredictably to both corners and the middle.",instructions:"Player reads each feed and responds with the correct pattern: deep cross from a corner, or a step-around forehand from the middle. Twelve balls, then rotate.",coaching_points:"Read the feed early, split-step, and pick a high-percentage target.",progression:"Coach mixes in a short ball that must be attacked.",tags:["decision","movement"]},
];

const existing = (await admin.from('drills').select('name')).data?.map(d => d.name.toLowerCase()) || [];
const rows = D.filter(d => !existing.includes(d.name.toLowerCase()));
if (rows.length) {
  const { error } = await admin.from('drills').insert(rows);
  if (error) { console.error('ERR', error.message); process.exit(1); }
}
const total = (await admin.from('drills').select('*', { count: 'exact', head: true })).count;
console.log(`Seeded ${rows.length} new drills. Library total: ${total}`);
