/**
 * The lineup as a printable page — for the clipboard at the courts.
 *
 * Opened in its own window and handed to the browser's print dialog, which
 * also offers "Save as PDF" — so there is no PDF library, and what prints is
 * exactly the sheet on screen, saved or not. White paper, black text, none of
 * the app's dark chrome.
 *
 * ⚠️ Carries no tokenised links, same as the group-chat text: a printout gets
 * left on a bench, and every confirm/withdraw link identifies one player.
 */
import { CLUB_TZ } from './clubTime';

export type PrintCourt = {
  courtNumber: number;
  courtType: 'singles' | 'doubles';
  names: string[];
  /** JTT: the round this line is played in. Adds a Round column when set. */
  round?: number | null;
};

export type PrintLineupInput = {
  teamName: string;
  matchAt: string;
  opponent?: string | null;
  isHome: boolean;
  location?: string | null;
  arrivalNote?: string | null;
  /** JTT: courts played at once. Printed so the other captain can check it. */
  courtFormat?: number | null;
  courts: PrintCourt[];
  /** Unsaved edits on screen — say so on the paper. */
  draft?: boolean;
  timeZone?: string;
};

export const PRINT_FOOTER = 'This roster was generated by clubmode.ai';

const ESC: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ESC[c]);

const lineLabel = (c: PrintCourt) =>
  `${c.courtType === 'singles' ? 'Singles' : 'Doubles'} ${c.courtNumber}`;

/** A complete HTML document that prints itself on load. */
export function lineupPrintHtml(input: PrintLineupInput): string {
  const tz = input.timeZone || CLUB_TZ;
  // Club time, always — the browser may be anywhere, and a 4pm match must say 4pm.
  const when = new Intl.DateTimeFormat('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZone: tz,
  }).format(new Date(input.matchAt));

  const byRound = input.courts.some((c) => c.round);
  const typeOrder = (c: PrintCourt) => (c.courtType === 'singles' ? 0 : 1);
  const courts = [...input.courts].sort((a, b) =>
    byRound
      ? (a.round ?? 99) - (b.round ?? 99) || typeOrder(a) - typeOrder(b) || a.courtNumber - b.courtNumber
      : a.courtNumber - b.courtNumber,
  );

  // Round cell spans its lines, so the paper reads "Round 1" once, not three times.
  const span = new Map<number, number>();
  for (const c of courts) if (c.round) span.set(c.round, (span.get(c.round) ?? 0) + 1);
  const printedRound = new Set<number>();

  const rows = courts
    .map((c) => {
      const names = c.names.filter((n) => n && n !== '—');
      let roundCell = '';
      if (byRound && c.round && !printedRound.has(c.round)) {
        printedRound.add(c.round);
        roundCell = `<td class="round" rowspan="${span.get(c.round)}">Round ${c.round}</td>`;
      } else if (byRound && !c.round) {
        roundCell = '<td class="round"></td>';
      }
      return `<tr>${roundCell}<td class="line">${lineLabel(c)}</td><td class="names">${
        names.length ? names.map(esc).join(' &nbsp;/&nbsp; ') : '<span class="muted">— default —</span>'
      }</td><td class="score"></td></tr>`;
    })
    .join('');

  const vs = input.opponent ? ` vs ${esc(input.opponent)}` : '';
  const where = `${input.isHome ? 'Home' : 'Away'}${input.location ? ` · ${esc(input.location)}` : ''}`;
  const meta = [
    where,
    input.courtFormat ? `${input.courtFormat}-court format` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${esc(input.teamName)} lineup — ${esc(when)}</title>
<style>
  @page { size: letter; margin: 14mm; }
  * { box-sizing: border-box; }
  body { margin: 0; padding: 24px 24px 72px; background: #fff; color: #0f172a;
         font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }
  h1 { font-size: 24px; margin: 0 0 4px; }
  .when { font-size: 16px; margin: 0 0 2px; }
  .meta, .note { font-size: 14px; color: #334155; margin: 0 0 2px; }
  .draft { display: inline-block; margin: 10px 0 0; padding: 4px 10px; border: 2px solid #0f172a;
           font-weight: 700; font-size: 13px; letter-spacing: .04em; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 16px; }
  th { text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: .06em;
       color: #475569; border-bottom: 2px solid #0f172a; padding: 8px 10px; }
  td { border-bottom: 1px solid #cbd5e1; padding: 12px 10px; vertical-align: middle; }
  td.round { font-weight: 700; white-space: nowrap; border-right: 1px solid #cbd5e1; }
  td.line { white-space: nowrap; color: #334155; width: 1%; }
  td.score { width: 22%; border-left: 1px solid #cbd5e1; }
  .muted { color: #94a3b8; }
  .footer { position: fixed; left: 0; right: 0; bottom: 16px; text-align: center; font-size: 14px; }
  .actions { margin-top: 24px; }
  .actions button { font-size: 15px; padding: 10px 18px; border-radius: 8px; border: 1px solid #0f172a;
                    background: #0f172a; color: #fff; cursor: pointer; }
  @media print { .actions { display: none; } body { padding: 0 0 48px; } .footer { bottom: 0; } }
</style></head>
<body>
  <h1>${esc(input.teamName)}${vs}</h1>
  <p class="when">${esc(when)}</p>
  <p class="meta">${meta}</p>
  ${input.arrivalNote?.trim() ? `<p class="note">${esc(input.arrivalNote.trim())}</p>` : ''}
  ${input.draft ? '<p class="draft">DRAFT — not yet saved or sent to the team</p>' : ''}
  <table>
    <thead><tr>${byRound ? '<th>Round</th>' : ''}<th>Line</th><th>Players</th><th>Score</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="actions"><button onclick="window.print()">Print / Save as PDF</button></div>
  <p class="footer"><strong>${PRINT_FOOTER}</strong></p>
  <script>window.addEventListener('load', function () { window.focus(); window.print(); });</script>
</body></html>`;
}
