import { describe, it, expect } from 'vitest';
import { lineupPrintHtml, PRINT_FOOTER } from './lineupPrint';

const base = {
  teamName: '10U Green Ball Fall 2026',
  // 23:00Z on Sep 13 is 4:00 PM in the club's time zone.
  matchAt: '2026-09-13T23:00:00.000Z',
  opponent: 'Orinda Country Club - 10U Green',
  isHome: false,
  location: 'Orinda Country Club',
  courts: [
    { courtNumber: 1, courtType: 'singles' as const, names: ['Miles Peter'], round: 1 },
    { courtNumber: 5, courtType: 'doubles' as const, names: ['Paloma Branson', 'Gavin Cohen'], round: 1 },
    { courtNumber: 2, courtType: 'singles' as const, names: ['Gavin Cohen'], round: 2 },
    { courtNumber: 6, courtType: 'doubles' as const, names: ['—', '—'], round: 2 },
  ],
};

describe('the printable lineup', () => {
  const html = lineupPrintHtml({ ...base, courtFormat: 2 });

  it('ends with the ClubMode line, in bold', () => {
    expect(PRINT_FOOTER).toBe('This roster was generated by clubmode.ai');
    expect(html).toContain(`<strong>${PRINT_FOOTER}</strong>`);
  });

  it('prints the match in club time, whatever the browser zone', () => {
    expect(html).toContain('Sunday, September 13, 2026 at 4:00 PM');
  });

  it('groups lines by round, singles before doubles, and says the format', () => {
    expect(html).toContain('<th>Round</th>');
    expect(html.indexOf('Round 1')).toBeLessThan(html.indexOf('Round 2'));
    expect(html.indexOf('Singles 1')).toBeLessThan(html.indexOf('Doubles 5'));
    expect(html.indexOf('Doubles 5')).toBeLessThan(html.indexOf('Singles 2'));
    expect(html).toContain('2-court format');
  });

  it('marks an uncovered line as a default instead of printing dashes', () => {
    expect(html).toContain('— default —');
  });

  it('has no round column for an adult sheet', () => {
    const adult = lineupPrintHtml({
      ...base,
      courts: base.courts.map(({ round: _round, ...c }) => c),
    });
    expect(adult).not.toContain('<th>Round</th>');
  });

  it('escapes names so a roster typo cannot break the page', () => {
    const odd = lineupPrintHtml({
      ...base,
      courts: [{ courtNumber: 1, courtType: 'singles', names: ['<b>Bobby</b> & Co'], round: 1 }],
    });
    expect(odd).toContain('&lt;b&gt;Bobby&lt;/b&gt; &amp; Co');
  });

  it('leaves room to write in the opponents — one line per player', () => {
    expect(html).toContain('<th>Opponents</th>');
    const cells = html.match(/<td class="opp">(.*?)<\/td>/g) ?? [];
    expect(cells).toHaveLength(4);
    const blanks = cells.map((c) => (c.match(/class="write"/g) ?? []).length);
    // singles 1, doubles 5, singles 2, doubles 6
    expect(blanks).toEqual([1, 2, 1, 2]);
  });

  it('gives a blank for the opponent team when it is not known yet', () => {
    expect(html).toContain('vs Orinda Country Club - 10U Green');
    const unknown = lineupPrintHtml({ ...base, opponent: null });
    expect(unknown).toContain('vs <span class="write inline"></span>');
  });

  it('says DRAFT only when the sheet on screen is unsaved', () => {
    expect(html).not.toContain('DRAFT');
    expect(lineupPrintHtml({ ...base, draft: true })).toContain('DRAFT');
  });
});
