/**
 * An event's sign-up poster, as a sheet of paper for the clubhouse wall.
 *
 * A QR code on its own is not a poster. Somebody walking past the pro shop has
 * to know what the event is, when it is, and why they would point a phone at a
 * square — so the code needs a headline, a date and a reason around it.
 *
 * THEMED FROM THE EVENT, via events.display_theme and the same palettes the
 * TV console uses. A US Open watch party prints in the navy and tournament
 * yellow; Wimbledon prints green; an unthemed event prints in ClubMode's own
 * colours. One column drives both screens, so the poster on the wall and the
 * TV inside the room match without anyone setting them up twice.
 *
 * TWO PRINT DECISIONS worth stating, because both look like mistakes:
 *
 *  1. The body is WHITE, not the theme's dark ground. A full-bleed dark poster
 *     drains an office laser, prints streaky on an inkjet, and clubs print
 *     these twenty at a time. The theme lives in a bold header band and the
 *     accents, which is what real event posters do anyway.
 *
 *  2. The QR sits on WHITE, always. A QR code needs dark modules on a light
 *     background to scan reliably; on navy, half the phones in the room fail
 *     and the poster has failed at its only job.
 *
 * pdf-lib with the standard Helvetica faces — no font files to embed, no
 * headless browser, so it renders the same locally and on a serverless
 * function.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage, type RGB } from 'pdf-lib';
import type { DisplayTheme } from './displayTheme';

const PAGE = { w: 612, h: 792 }; // US Letter, the paper in every club's printer
const MARGIN = 54;
const CONTENT_W = PAGE.w - MARGIN * 2;

/** #rrggbb into pdf-lib's 0-1 triples. */
function hex(color: string) {
  const h = (color || '').replace('#', '').trim();
  const full = h.length === 3 ? h.replace(/./g, (c) => c + c) : h;
  const n = parseInt(full, 16);
  if (Number.isNaN(n)) return rgb(0, 0, 0);
  return rgb(((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255);
}

const INK = rgb(0.09, 0.12, 0.15);
const MUTED = rgb(0.42, 0.45, 0.48);

/**
 * The largest size at which `text` still fits `width`, down to `min`.
 *
 * Event names run from "Ladies B" to "Sleepy Hollow Level 5 Junior 12s & 14s
 * Singles Championship", and a poster headline that silently overflows the
 * page is worse than a smaller one that fits.
 */
function fitSize(text: string, font: PDFFont, width: number, max: number, min: number): number {
  let size = max;
  while (size > min && font.widthOfTextAtSize(text, size) > width) size -= 1;
  return size;
}

/**
 * Draw text with letter-spacing, one glyph at a time.
 *
 * This pdf-lib build has no `characterSpacing` option, and tracking is not
 * cosmetic here: a kicker like US OPEN WATCH PARTY set tight reads as one long
 * word across a room. Returns the width drawn so callers can centre it.
 */
function drawTracked(
  page: PDFPage,
  text: string,
  opts: { x: number; y: number; size: number; font: PDFFont; color: RGB; tracking: number },
): number {
  let x = opts.x;
  for (const ch of text) {
    page.drawText(ch, { x, y: opts.y, size: opts.size, font: opts.font, color: opts.color });
    x += opts.font.widthOfTextAtSize(ch, opts.size) + opts.tracking;
  }
  return x - opts.tracking - opts.x;
}

/** Width that drawTracked will occupy, for centring before drawing. */
function trackedWidth(text: string, font: PDFFont, size: number, tracking: number): number {
  if (!text.length) return 0;
  return font.widthOfTextAtSize(text, size) + tracking * (text.length - 1);
}

/** Greedy wrap against the font's measured widths. */
function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const out: string[] = [];
  let line = '';
  for (const word of text.split(/\s+/).filter(Boolean)) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= width) {
      line = candidate;
    } else {
      if (line) out.push(line);
      line = word;
    }
  }
  if (line) out.push(line);
  return out;
}

export type PosterInput = {
  eventName: string;
  /** Already formatted in CLUB time by the caller — this file does no timezone maths. */
  whenLine: string | null;
  venue: string | null;
  eventCode: string;
  /** The URL the QR encodes, shown in text too for anyone who will not scan. */
  publicUrl: string;
  /** PNG bytes of the QR, generated by the caller. */
  qrPng: Uint8Array;
  theme: DisplayTheme;
  /** Optional club or event mark, PNG or JPG bytes. */
  logo?: { bytes: Uint8Array; type: 'png' | 'jpg' } | null;
};

export async function buildEventPoster(input: PosterInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`${input.eventName} — sign-up poster`);
  const page = doc.addPage([PAGE.w, PAGE.h]);

  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);

  const ground = hex(input.theme.ground);
  const accent = hex(input.theme.accent);

  /*
   * The club's own mark, top-right of the band.
   *
   * Embedded BEFORE the band is measured, because a logo narrows the width the
   * headline gets — and the headline's size decides how tall the band is. It
   * was at the bottom of the page originally, where a wide logo overlapped the
   * centred URL line.
   */
  let headerRight = PAGE.w - MARGIN;
  let logoImage: Awaited<ReturnType<typeof doc.embedPng>> | null = null;
  let logoBox = { w: 0, h: 56 };
  if (input.logo) {
    try {
      logoImage =
        input.logo.type === 'png'
          ? await doc.embedPng(input.logo.bytes)
          : await doc.embedJpg(input.logo.bytes);
      logoBox.w = Math.min((logoImage.width / logoImage.height) * logoBox.h, 180);
      headerRight = PAGE.w - MARGIN - logoBox.w - 20;
    } catch {
      // A logo that will not decode must not cost the club its poster.
      logoImage = null;
    }
  }
  /** Text width available in the band — narrower when a logo is sitting there. */
  const headerW = headerRight - MARGIN;

  // ------------------------------------------------------------ header band
  /*
   * Measured first, then drawn — the band is sized to its content.
   *
   * It used to be a fixed 196pt with the date pinned to the bottom, which left
   * a visible gap under a one-line name AND collided with a two-line one: a
   * 40pt name over two lines ran straight through the date. Laying it out
   * top-down means the long championship names fit and the short ones do not
   * leave a hole.
   */
  const KICKER_SIZE = 13;
  const WHEN_SIZE = 15;
  const PAD_TOP = 40;
  const PAD_BOTTOM = 26;

  const nameSize = fitSize(input.eventName, bold, headerW, 40, 20);
  const nameLines = wrap(input.eventName, bold, nameSize, headerW).slice(0, 2);

  const bandH =
    PAD_TOP +
    (input.theme.kicker ? KICKER_SIZE + 16 : 0) +
    nameLines.length * (nameSize + 6) +
    (input.whenLine ? WHEN_SIZE + 12 : 0) +
    PAD_BOTTOM;

  page.drawRectangle({ x: 0, y: PAGE.h - bandH, width: PAGE.w, height: bandH, color: ground });
  if (logoImage) {
    page.drawImage(logoImage, {
      x: PAGE.w - MARGIN - logoBox.w,
      y: PAGE.h - 34 - logoBox.h,
      width: logoBox.w,
      height: logoBox.h,
    });
  }
  // A stripe of the accent under the band, so the theme reads even in mono.
  page.drawRectangle({ x: 0, y: PAGE.h - bandH - 8, width: PAGE.w, height: 8, color: accent });

  let y = PAGE.h - PAD_TOP - KICKER_SIZE;

  if (input.theme.kicker) {
    drawTracked(page, input.theme.kicker.toUpperCase(), {
      x: MARGIN,
      y,
      size: KICKER_SIZE,
      font: bold,
      color: accent,
      tracking: 2.4,
    });
    y -= 16;
  }

  y -= nameSize;
  for (const line of nameLines) {
    page.drawText(line, { x: MARGIN, y, size: nameSize, font: bold, color: rgb(1, 1, 1) });
    y -= nameSize + 6;
  }

  if (input.whenLine) {
    y -= 6;
    page.drawText(input.whenLine, {
      x: MARGIN,
      y,
      size: WHEN_SIZE,
      font: regular,
      color: rgb(1, 1, 1),
    });
  }

  // ------------------------------------------------------------------- QR
  // Centred, large, and on white. 300pt is about 4 inches — readable by a
  // phone held at arm's length, which is how people scan a wall.
  const QR_SIZE = 300;
  const qrImage = await doc.embedPng(input.qrPng);
  const qrX = (PAGE.w - QR_SIZE) / 2;
  const qrY = PAGE.h - bandH - 8 - 46 - QR_SIZE;

  // A quiet border so the code never sits flush against anything.
  page.drawRectangle({
    x: qrX - 14,
    y: qrY - 14,
    width: QR_SIZE + 28,
    height: QR_SIZE + 28,
    borderColor: accent,
    borderWidth: 3,
    color: rgb(1, 1, 1),
  });
  page.drawImage(qrImage, { x: qrX, y: qrY, width: QR_SIZE, height: QR_SIZE });

  const scanLine = 'Scan for live courts, matchups and standings';
  page.drawText(scanLine, {
    x: (PAGE.w - bold.widthOfTextAtSize(scanLine, 15)) / 2,
    y: PAGE.h - bandH - 8 - 30,
    size: 15,
    font: bold,
    color: INK,
  });

  // ------------------------------------------------------------- the code
  let below = qrY - 52;

  const codeLabel = 'Or enter code';
  page.drawText(codeLabel, {
    x: (PAGE.w - regular.widthOfTextAtSize(codeLabel, 12)) / 2,
    y: below,
    size: 12,
    font: regular,
    color: MUTED,
  });
  below -= 38;

  const CODE_TRACKING = 6;
  let codeSize = fitSize(input.eventCode, bold, CONTENT_W, 46, 24);
  // fitSize measures untracked text, so re-check against the tracked width or
  // a long code runs off the page.
  while (codeSize > 24 && trackedWidth(input.eventCode, bold, codeSize, CODE_TRACKING) > CONTENT_W) {
    codeSize -= 1;
  }
  drawTracked(page, input.eventCode, {
    x: (PAGE.w - trackedWidth(input.eventCode, bold, codeSize, CODE_TRACKING)) / 2,
    y: below,
    size: codeSize,
    font: bold,
    color: ground,
    tracking: CODE_TRACKING,
  });
  below -= 30;

  page.drawText(input.publicUrl.replace(/^https?:\/\//, ''), {
    x: (PAGE.w - regular.widthOfTextAtSize(input.publicUrl.replace(/^https?:\/\//, ''), 12)) / 2,
    y: below,
    size: 12,
    font: regular,
    color: MUTED,
  });

  // ---------------------------------------------------------------- footer
  const footerY = MARGIN + 16;
  page.drawRectangle({ x: MARGIN, y: footerY + 30, width: CONTENT_W, height: 2, color: accent });

  if (input.venue) {
    page.drawText(input.venue, { x: MARGIN, y: footerY, size: 11, font: bold, color: INK });
  }
  const noLogin = 'No app. No login.';
  page.drawText(noLogin, {
    x: PAGE.w - MARGIN - regular.widthOfTextAtSize(noLogin, 11),
    y: footerY,
    size: 11,
    font: regular,
    color: MUTED,
  });

  return doc.save();
}
